on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'yarn'
      - run: yarn config set @folio:registry https://repository.folio.org/repository/npm-folioci/
      #- run: yarn install --frozen-lockfile --ignore-scripts --non-interactive
      - run: yarn install --ignore-scripts --non-interactive
      - run: yarn run test:jest
